name: Oreo Theme ğŸª
id: oreo-theme
settings:
  - id: general-settings
    title: General Settings âš™
    title.zh: å¸¸è§„è®¾ç½® âš™
    type: heading
    level: 2
    collapsed: true
  - id: button-radius
    title: Button Radius
    title.zh: æŒ‰é’®åœ†è§’åŠå¾„
    type: variable-number
    default: 10
    format: px
  - id: checkbox-radius
    title: Checkbox Radius
    title.zh: å¤é€‰æ¡†åœ†è§’åŠå¾„
    type: variable-number
    default: 50
    format: "%"
  - id: checkbox-size
    title: Checkbox Size
    title.zh: å¤é€‰æ¡†å¤§å°
    type: variable-number
    default: 16
    format: px
  - id: checkbox-margin-inline-start
    title: Checkbox Margin Inline Start
    title.zh: å¤é€‰æ¡†èµ·å§‹å†…è¾¹è·
    type: variable-number
    default: 8
    format: px
  - id: popover-width
    title: Popover Width
    title.zh: å¼¹å‡ºæ¡†å®½åº¦
    type: variable-number
    default: 300
    format: px
  - id: popover-height
    title: Popover Height
    title.zh: å¼¹å‡ºæ¡†é«˜åº¦
    type: variable-text
    default: auto
  - id: popover-max-height
    title: Popover Max Height
    title.zh: å¼¹å‡ºæ¡†æœ€å¤§é«˜åº¦
    type: variable-number
    default: 400
    format: px
  - id: popover-font-size
    title: Popover Font Size
    title.zh: å¼¹å‡ºæ¡†å­—ä½“å¤§å°
    type: variable-number
    default: 14
    format: px
  - id: popover-pdf-width
    title: Popover PDF Width
    title.zh: PDF æ–‡ä»¶é¢„è§ˆå®½åº¦
    type: variable-number
    default: 600
    format: px
  - id: popover-pdf-height
    title: Popover PDF Height
    title.zh: PDF æ–‡ä»¶é¢„è§ˆé«˜åº¦
    type: variable-number
    default: 800
    format: px
  - id: heading-spacing
    title: Heading Spacing
    title.zh: å¤´éƒ¨é—´è·
    type: variable-number
    default: 20
    format: px
  - id: heading-font-settings
    title: Heading Font Settings ğŸ–‹ï¸
    title.zh: æ ‡é¢˜å­—ä½“è®¾ç½® ğŸ–‹ï¸
    type: heading
    level: 2
    collapsed: true
  - id: h1-font
    title: H1 Font
    title.zh: H1 å­—ä½“
    type: variable-text
    default: "Arial, sans-serif"
  - id: h2-font
    title: H2 Font
    title.zh: H2 å­—ä½“
    type: variable-text
    default: "Arial, sans-serif"
  - id: h3-font
    title: H3 Font
    title.zh: H3 å­—ä½“
    type: variable-text
    default: "Arial, sans-serif"
  - id: h4-font
    title: H4 Font
    title.zh: H4 å­—ä½“
    type: variable-text
    default: "Arial, sans-serif"
  - id: h5-font
    title: H5 Font
    title.zh: H5 å­—ä½“
    type: variable-text
    default: "Arial, sans-serif"
  - id: h6-font
    title: H6 Font
    title.zh: H6 å­—ä½“
    type: variable-text
    default: "Arial, sans-serif"
  - id: heading-line-height-settings
    title: Heading Line Height Settings ğŸ“
    title.zh: æ ‡é¢˜è¡Œé«˜è®¾ç½® ğŸ“
    type: heading
    level: 2
    collapsed: true
  - id: h1-line-height
    title: H1 Line Height
    title.zh: H1 è¡Œé«˜
    type: variable-number
    default: 1.5
  - id: h2-line-height
    title: H2 Line Height
    title.zh: H2 è¡Œé«˜
    type: variable-number
    default: 1.5
  - id: h3-line-height
    title: H3 Line Height
    title.zh: H3 è¡Œé«˜
    type: variable-number
    default: 1.5
  - id: h4-line-height
    title: H4 Line Height
    title.zh: H4 è¡Œé«˜
    type: variable-number
    default: 1.5
  - id: h5-line-height
    title: H5 Line Height
    title.zh: H5 è¡Œé«˜
    type: variable-number
    default: 1.5
  - id: h6-line-height
    title: H6 Line Height
    title.zh: H6 è¡Œé«˜
    type: variable-number
    default: 1.5
  - id: heading-size-settings
    title: Heading Size Settings ğŸ” 
    title.zh: æ ‡é¢˜å¤§å°è®¾ç½® ğŸ” 
    type: heading
    level: 2
    collapsed: true
  - id: h1-size
    title: H1 Size
    title.zh: H1 å¤§å°
    type: variable-number
    default: 2
    format: em
  - id: h2-size
    title: H2 Size
    title.zh: H2 å¤§å°
    type: variable-number
    default: 1.75
    format: em
  - id: h3-size
    title: H3 Size
    title.zh: H3 å¤§å°
    type: variable-number
    default: 1.5
    format: em
  - id: h4-size
    title: H4 Size
    title.zh: H4 å¤§å°
    type: variable-number
    default: 1.25
    format: em
  - id: h5-size
    title: H5 Size
    title.zh: H5 å¤§å°
    type: variable-number
    default: 1
    format: em
  - id: h6-size
    title: H6 Size
    title.zh: H6 å¤§å°
    type: variable-number
    default: 0.875
    format: em
  - id: heading-style-settings
    title: Heading Style Settings ğŸ–Œï¸
    title.zh: æ ‡é¢˜æ ·å¼è®¾ç½® ğŸ–Œï¸
    type: heading
    level: 2
    collapsed: true
  - id: h1-style
    title: H1 Style
    title.zh: H1 æ ·å¼
    type: variable-select
    default: normal
    options:
      - normal
      - italic
  - id: h2-style
    title: H2 Style
    title.zh: H2 æ ·å¼
    type: variable-select
    default: normal
    options:
      - normal
      - italic
  - id: h3-style
    title: H3 Style
    title.zh: H3 æ ·å¼
    type: variable-select
    default: normal
    options:
      - normal
      - italic
  - id: h4-style
    title: H4 Style
    title.zh: H4 æ ·å¼
    type: variable-select
    default: normal
    options:
      - normal
      - italic
  - id: h5-style
    title: H5 Style
    title.zh: H5 æ ·å¼
    type: variable-select
    default: normal
    options:
      - normal
      - italic
  - id: h6-style
    title: H6 Style
    title.zh: H6 æ ·å¼
    type: variable-select
    default: normal
    options:
      - normal
      - italic
  - id: heading-variant-settings
    title: Heading Variant Settings ğŸ·ï¸
    title.zh: æ ‡é¢˜å˜ä½“è®¾ç½® ğŸ·ï¸
    type: heading
    level: 2
    collapsed: true
  - id: h1-variant
    title: H1 Variant
    title.zh: H1 å˜ä½“
    type: variable-select
    default: normal
    options:
      - normal
      - small-caps
  - id: h2-variant
    title: H2 Variant
    title.zh: H2 å˜ä½“
    type: variable-select
    default: normal
    options:
      - normal
      - small-caps
  - id: h3-variant
    title: H3 Variant
    title.zh: H3 å˜ä½“
    type: variable-select
    default: normal
    options:
      - normal
      - small-caps
  - id: h4-variant
    title: H4 Variant
    title.zh: H4 å˜ä½“
    type: variable-select
    default: normal
    options:
      - normal
      - small-caps
  - id: h5-variant
    title: H5 Variant
    title.zh: H5 å˜ä½“
    type: variable-select
    default: normal
    options:
      - normal
      - small-caps
  - id: h6-variant
    title: H6 Variant
    title.zh: H6 å˜ä½“
    type: variable-select
    default: normal
    options:
      - normal
      - small-caps
  - id: heading-weight-settings
    title: Heading Weight Settings ğŸ‹ï¸
    title.zh: æ ‡é¢˜ç²—ç»†è®¾ç½® ğŸ‹ï¸
    type: heading
    level: 2
    collapsed: true
  - id: h1-weight
    title: H1 Weight
    title.zh: H1 ç²—ç»†
    type: variable-select
    default: bold
    options:
      - normal
      - bold
  - id: h2-weight
    title: H2 Weight
    title.zh: H2 ç²—ç»†
    type: variable-select
    default: bold
    options:
      - normal
      - bold
  - id: h3-weight
    title: H3 Weight
    title.zh: H3 ç²—ç»†
    type: variable-select
    default: bold
    options:
      - normal
      - bold
  - id: h4-weight
    title: H4 Weight
    title.zh: H4 ç²—ç»†
    type: variable-select
    default: bold
    options:
      - normal
      - bold
  - id: h5-weight
    title: H5 Weight
    title.zh: H5 ç²—ç»†
    type: variable-select
    default: bold
    options:
      - normal
      - bold
  - id: h6-weight
    title: H6 Weight
    title.zh: H6 ç²—ç»†
    type: variable-select
    default: bold
    options:
      - normal
      - bold
  - id: heading-formatting
    title: Heading Formatting
    title.zh: æ ‡é¢˜æ ¼å¼
    type: variable-color
    default: "#888888"
  - id: link-settings
    title: Link Settings ğŸ”—
    title.zh: é“¾æ¥è®¾ç½® ğŸ”—
    type: heading
    level: 2
    collapsed: true
  - id: link-color
    title: Link Color
    title.zh: é“¾æ¥é¢œè‰²
    type: variable-color
    default: "#1e90ff"
  - id: link-color-hover
    title: Link Hover Color
    title.zh: é“¾æ¥æ‚¬åœé¢œè‰²
    type: variable-color
    default: "#1c86ee"
  - id: link-decoration
    title: Link Decoration
    title.zh: é“¾æ¥è£…é¥°
    type: variable-select
    default: underline
    options:
      - none
      - underline
  - id: link-decoration-hover
    title: Link Hover Decoration
    title.zh: é“¾æ¥æ‚¬åœè£…é¥°
    type: variable-select
    default: underline
    options:
      - none
      - underline
  - id: link-decoration-thickness
    title: Link Decoration Thickness
    title.zh: é“¾æ¥è£…é¥°åšåº¦
    type: variable-number
    default: 1
    format: px
  - id: link-weight
    title: Link Weight
    title.zh: é“¾æ¥ç²—ç»†
    type: variable-select
    default: normal
    options:
      - normal
      - bold
  - id: link-unresolved-color
    title: Unresolved Link Color
    title.zh: æœªè§£æé“¾æ¥é¢œè‰²
    type: variable-color
    default: "#ff4500"
  - id: link-unresolved-opacity
    title: Unresolved Link Opacity
    title.zh: æœªè§£æé“¾æ¥ä¸é€æ˜åº¦
    type: variable-number
    default: 0.7
  - id: link-unresolved-filter
    title: Unresolved Link Filter
    title.zh: æœªè§£æé“¾æ¥æ»¤é•œ
    type: variable-text
    default: brightness(0.8)
  - id: link-unresolved-decoration-style
    title: Unresolved Link Decoration Style
    title.zh: æœªè§£æé“¾æ¥è£…é¥°æ ·å¼
    type: variable-select
    default: dashed
    options:
      - none
      - underline
      - dashed
      - dotted
  - id: link-unresolved-decoration-color
    title: Unresolved Link Decoration Color
    title.zh: æœªè§£æé“¾æ¥è£…é¥°é¢œè‰²
    type: variable-color
    default: "#ff4500"
  - id: link-external-color
    title: External Link Color
    title.zh: å¤–éƒ¨é“¾æ¥é¢œè‰²
    type: variable-color
    default: "#32cd32"
  - id: link-external-color-hover
    title: External Link Hover Color
    title.zh: å¤–éƒ¨é“¾æ¥æ‚¬åœé¢œè‰²
    type: variable-color
    default: "#2eb82e"
  - id: link-external-decoration
    title: External Link Decoration
    title.zh: å¤–éƒ¨é“¾æ¥è£…é¥°
    type: variable-select
    default: underline
    options:
      - none
      - underline
  - id: link-external-decoration-hover
    title: External Link Hover Decoration
    title.zh: å¤–éƒ¨é“¾æ¥æ‚¬åœè£…é¥°
    type: variable-select
    default: underline
    options:
      - none
      - underline
  - id: inline-title-settings
    title: Inline Title Settings ğŸ–‹ï¸
    title.zh: è¡Œå†…æ ‡é¢˜è®¾ç½® ğŸ–‹ï¸
    type: heading
    level: 2
    collapsed: true
  - id: inline-title-color
    title: Inline Title Color
    title.zh: è¡Œå†…æ ‡é¢˜é¢œè‰²
    type: variable-color
    default: "#000000"
  - id: inline-title-font
    title: Inline Title Font
    title.zh: è¡Œå†…æ ‡é¢˜å­—ä½“
    type: variable-text
    default: "Arial, sans-serif"
  - id: inline-title-line-height
    title: Inline Title Line Height
    title.zh: è¡Œå†…æ ‡é¢˜è¡Œé«˜
    type: variable-number
    default: 1.5
  - id: inline-title-size
    title: Inline Title Size
    title.zh: è¡Œå†…æ ‡é¢˜å¤§å°
    type: variable-number
    default: 1.2
    format: em
  - id: inline-title-style
    title: Inline Title Style
    title.zh: è¡Œå†…æ ‡é¢˜æ ·å¼
    type: variable-select
    default: normal
    options:
      - normal
      - italic
  - id: inline-title-variant
    title: Inline Title Variant
    title.zh: è¡Œå†…æ ‡é¢˜å˜ä½“
    type: variable-select
    default: normal
    options:
      - normal
      - small-caps
  - id: inline-title-weight
    title: Inline Title Weight
    title.zh: è¡Œå†…æ ‡é¢˜ç²—ç»†
    type: variable-select
    default: bold
    options:
      - normal
      - bold
  - id: code-settings
    title: Code Block Settings ğŸ’»
    title.zh: ä»£ç å—è®¾ç½® ğŸ’»
    type: heading
    level: 2
    collapsed: true
  - id: code-background-dark
    title: Dark Mode Code Background
    title.zh: æš—æ¨¡å¼ä¸‹ä»£ç èƒŒæ™¯é¢œè‰²
    type: variable-color
    default: "#2d2d2d"
  - id: code-normal-dark
    title: Dark Mode Code Normal Color
    title.zh: æš—æ¨¡å¼ä¸‹éé«˜äº®è¯­æ³•é¢œè‰²
    type: variable-color
    default: "#ffffff"
  - id: code-comment-dark
    title: Dark Mode Code Comment Color
    title.zh: æš—æ¨¡å¼ä¸‹æ³¨é‡Šé¢œè‰²
    type: variable-color
    default: "#999988"
  - id: code-function-dark
    title: Dark Mode Code Function Color
    title.zh: æš—æ¨¡å¼ä¸‹å‡½æ•°é¢œè‰²
    type: variable-color
    default: "#a6e22e"
  - id: code-important-dark
    title: Dark Mode Code Important Color
    title.zh: æš—æ¨¡å¼ä¸‹é‡è¦å†…å®¹, æ­£åˆ™è¡¨è¾¾å¼é¢œè‰²
    type: variable-color
    default: "#f92672"
  - id: code-keyword-dark
    title: Dark Mode Code Keyword Color
    title.zh: æš—æ¨¡å¼ä¸‹å…³é”®è¯é¢œè‰²
    type: variable-color
    default: "#f92672"
  - id: code-operator-dark
    title: Dark Mode Code Operator Color
    title.zh: æš—æ¨¡å¼ä¸‹æ“ä½œç¬¦é¢œè‰²
    type: variable-color
    default: "#f92672"
  - id: code-property-dark
    title: Dark Mode Code Property Color
    title.zh: æš—æ¨¡å¼ä¸‹å±æ€§é¢œè‰²
    type: variable-color
    default: "#66d9ef"
  - id: code-punctuation-dark
    title: Dark Mode Code Punctuation Color
    title.zh: æš—æ¨¡å¼ä¸‹æ ‡ç‚¹é¢œè‰²
    type: variable-color
    default: "#ffffff"
  - id: code-string-dark
    title: Dark Mode Code String Color
    title.zh: æš—æ¨¡å¼ä¸‹å­—ç¬¦ä¸²é¢œè‰²
    type: variable-color
    default: "#e6db74"
  - id: code-tag-dark
    title: Dark Mode Code Tag Color
    title.zh: æš—æ¨¡å¼ä¸‹æ ‡ç­¾, ç¬¦å·, å¸¸é‡é¢œè‰²
    type: variable-color
    default: "#a6e22e"
  - id: code-value-dark
    title: Dark Mode Code Value Color
    title.zh: æš—æ¨¡å¼ä¸‹å€¼é¢œè‰²
    type: variable-color
    default: "#ae81ff"
  - id: code-background-light
    title: Light Mode Code Background
    title.zh: äº®æ¨¡å¼ä¸‹ä»£ç èƒŒæ™¯é¢œè‰²
    type: variable-color
    default: "#f5f5f5"
  - id: code-normal-light
    title: Light Mode Code Normal Color
    title.zh: äº®æ¨¡å¼ä¸‹éé«˜äº®è¯­æ³•é¢œè‰²
    type: variable-color
    default: "#000000"
  - id: code-comment-light
    title: Light Mode Code Comment Color
    title.zh: äº®æ¨¡å¼ä¸‹æ³¨é‡Šé¢œè‰²
    type: variable-color
    default: "#6a737d"
  - id: code-function-light
    title: Light Mode Code Function Color
    title.zh: äº®æ¨¡å¼ä¸‹å‡½æ•°é¢œè‰²
    type: variable-color
    default: "#6f42c1"
  - id: code-important-light
    title: Light Mode Code Important Color
    title.zh: äº®æ¨¡å¼ä¸‹é‡è¦å†…å®¹, æ­£åˆ™è¡¨è¾¾å¼é¢œè‰²
    type: variable-color
    default: "#d73a49"
  - id: code-keyword-light
    title: Light Mode Code Keyword Color
    title.zh: äº®æ¨¡å¼ä¸‹å…³é”®è¯é¢œè‰²
    type: variable-color
    default: "#d73a49"
  - id: code-operator-light
    title: Light Mode Code Operator Color
    title.zh: äº®æ¨¡å¼ä¸‹æ“ä½œç¬¦é¢œè‰²
    type: variable-color
    default: "#d73a49"
  - id: code-property-light
    title: Light Mode Code Property Color
    title.zh: äº®æ¨¡å¼ä¸‹å±æ€§é¢œè‰²
    type: variable-color
    default: "#005cc5"
  - id: code-punctuation-light
    title: Light Mode Code Punctuation Color
    title.zh: äº®æ¨¡å¼ä¸‹æ ‡ç‚¹é¢œè‰²
    type: variable-color
    default: "#24292e"
  - id: code-string-light
    title: Light Mode Code String Color
    title.zh: äº®æ¨¡å¼ä¸‹å­—ç¬¦ä¸²é¢œè‰²
    type: variable-color
    default: "#032f62"
  - id: code-tag-light
    title: Light Mode Code Tag Color
    title.zh: äº®æ¨¡å¼ä¸‹æ ‡ç­¾, ç¬¦å·, å¸¸é‡é¢œè‰²
    type: variable-color
    default: "#22863a"
  - id: code-value-light
    title: Light Mode Code Value Color
    title.zh: äº®æ¨¡å¼ä¸‹å€¼é¢œè‰²
    type: variable-color
    default: "#b31d28"
  - id: alternative-checkboxes
    title: Alternative Checkboxes âœ…
    title.zh: å…¶ä»–å¤é€‰æ¡†æ ·å¼ âœ…
    type: heading
    level: 2
    collapsed: true
  - id: enable-alternative-checkboxes
    title: Enable Alternative Checkboxes
    title.zh: å¯ç”¨å…¶ä»–å¤é€‰æ¡†æ ·å¼
    description: Disable this if you are using your own implementation via a CSS Snippet.
    description.zh: å¦‚æœæ‚¨æ­£åœ¨ä½¿ç”¨è‡ªå·±çš„ CSS ç‰‡æ®µå®ç°è¿™ä¸€åŠŸèƒ½ï¼Œè¯·ç¦ç”¨æ­¤åŠŸèƒ½ã€‚
    default: true
    type: class-toggle
  - id: expreiental-feature
    title: Experimental Features ğŸ§ª
    title.zh: å®éªŒæ€§åŠŸèƒ½ ğŸ§ª
    type: heading
    level: 2
    collapsed: true
  - id: oreo-tab-style
    title: Tab Style
    title.zh: Tabæ ·å¼
    type: class-select
    allowEmpty: false
    default: oreo-default-tab
    options:
      - label: Default
        value: oreo-default-tab
      - label: Depth
        value: oreo-depth-tab-toggle
      - label: Minimalistic
        value: oreo-mini-tab-toggle
      - label: Safari-style (Animated)
        value: oreo-alternate-tab-toggle
      - label: Safari-style (Vanilla)
        value: oreo-safari-tab-toggle
  - id: Credits
    title: Support Others ğŸ‡
    title.zh: æ”¯æŒä»–äºº ğŸ‡
    description: This theme cannot have been made without the help of these people, please support them if you can!
    description.zh: è¿™ä¸ªä¸»é¢˜çš„åˆ¶ä½œç¦»ä¸å¼€è¿™äº›äººçš„å¸®åŠ©ï¼Œå¦‚æœä½ æœ‰èƒ½åŠ›ï¼Œè¯·æ”¯æŒä»–ä»¬ï¼
    type: heading
    level: 2
    collapsed: true
  - id: anuppuccin-url-donate
    title: anubisnekhet for different tabs
    title.zh: anubisnekhet ä¸ä¸€æ ·çš„tabç•Œé¢
    description: "Support link: [buy him a coffee](https://www.buymeacoffee.com/anubisnekhet)"
    description.zh: "æ”¯æŒé“¾æ¥: [ç»™ä»–ä¹°æ¯å’–å•¡](https://www.buymeacoffee.com/anubisnekhet)"
    type: info-text
    markdown: true
  - id: kepano-url-donate
    title: kepano for different check boxes
    title.zh: kepano ä¸åŒçš„å¤é€‰æ¡†æ ·å¼
    description: "Support link: [buy him a coffee](https://www.buymeacoffee.com/kepano)"
    description.zh: "æ”¯æŒé“¾æ¥: [ç»™ä»–ä¹°æ¯å’–å•¡](https://www.buymeacoffee.com/kepano)"
    type: info-text
    markdown: true
  - id: Korcz-url-donate
    title: Korcz for switching between checkboxes
    title.zh: Korcz åˆ‡æ¢å¤é€‰æ¡†æ ·å¼
    description: "Support link: This kind man did not leave a support link, so here is his [Github homepage](https://github.com/damiankorcz)"
    description.zh: "æ”¯æŒé“¾æ¥: è¿™ä½å¥½å¿ƒäººå¹¶æœªç•™ä¸‹èµåŠ©é“¾æ¥ï¼Œè¯·è‡ªè¡Œå‰å¾€ä»–çš„[Githubä¸»é¡µ](https://github.com/damiankorcz)"
    type: info-text
    markdown: true
  - id: author-info
    title: Author Information â„¹
    title.zh: ä½œè€…ä¿¡æ¯ â„¹
    type: heading
    level: 2
    collapsed: false
  - id: author
    title: Author
    title.zh: ä½œè€…
    type: info-text
    description: "Oreo Theme created with â¤ï¸ by carols12352. Support at: BuyMeACoffee/(QAQ due to regional differences you cannot buy me a coffee, just enjoy the theme and provide feedback!)"
    description.zh: "Oreo ä¸»é¢˜ç”± carols12352 åˆ›å»ºã€‚æ”¯æŒè¯·è®¿é—®: BuyMeACoffee/(QAQ å› ä¸ºåœ°åŒºæ”¿ç­–åŸå› ä½ è¿˜ä¸èƒ½ç»™æˆ‘ä¹°ä¸€æ¯å’–å•¡ï¼Œè¯·äº«å—ä¸»é¢˜å¹¶ä¸”åŠæ—¶ç»™å‡ºåé¦ˆå°±å¥½ï¼)"
    markdown: false
