name: ğŸµ Comfort Light Theme
id: comfort-light-theme
settings:
  - id: background-primary
    title: Background-primary Color
    title.zh: ä¸€çº§èƒŒæ™¯è‰²
    type: variable-themed-color
    format: hex
    opacity: false
    default-light: "#fcfef3"
    default-dark: "#000000"
  - id: background-secondary
    title: Background-secondary Color
    title.zh: äºŒçº§èƒŒæ™¯è‰²
    type: variable-themed-color
    format: hex
    opacity: false
    default-light: "#f8f6ea"
    default-dark: "#000000"
  - id: background-secondary-alt
    title: background-secondary-alt Color
    title.zh: é¡¶éƒ¨å¯¼èˆªè‰²
    type: variable-themed-color
    format: hex
    opacity: false
    default-light: "#a3d5aa"
    default-dark: "#000000"
  - id: tab-container-background
    title: tab-container-background Color
    title.zh: å¯¼èˆªè‰²
    type: variable-themed-color
    format: hex
    opacity: false
    default-light: "#a3d5aa"
    default-dark: "#000000"
  - id: ribbon-background
    title: ribbon-background Color
    title.zh: æœ€å·¦è¾¹çŠ¶æ€æ 
    type: variable-color
    format: hex
    opacity: false
    default: "#a3d5aa"
  - id: font-family
    title: font-family
    description: Font used for the user interface
    type: variable-text
    default: å®‹ä½“, SimSun, -apple-system, sans-serif
