name: Generate preview images (A-D)
on:
  workflow_dispatch:

jobs:
  target_list:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.value }}
    steps:
      - id: matrix
        run: |
          echo "value=[\"80s-neon\", \"abate\", \"abecedarium\", \"absolutegruv\", \"abyssal\", \"adrenaline\", \"adwaita\", \"agate\", \"al-dente\", \"allium\", \"anuppuccin\", \"apatheia\", \"apex\", \"arcane\", \"atom\", \"atomus\", \"aura-dark\", \"aura\", \"aurora-twilight\", \"aurora\", \"autotape\", \"ayu-light-mirage\", \"ayu-mirage\", \"base2tone\", \"behave-dark\", \"big-bold\", \"black\", \"blackbird\", \"blossom\", \"blue-topaz\", \"bolt\", \"border\", \"bossidian\", \"brainhack\", \"brutalism\", \"buena-vista\", \"carbon\", \"cardstock\", \"catppuccin\", \"celestial-night\", \"charcoal\", \"chiaroscuroflow\", \"christmas\", \"cobalt-peacock\", \"colored-candy\", \"comfort-color-dark\", \"comfort-dark\", \"comfort-smooth\", \"comfort\", \"covert\", \"creature\", \"creme-brulee\", \"cyber-glow\", \"cybertron-shifted\", \"cybertron\", \"dark-castle\", \"dark-clarity\", \"dark-graphite-pie\", \"dark-graphite\", \"dark-moss\", \"darkember\", \"darkyan\", \"dawn\", \"dayspring\", \"deeper-work\", \"default\", \"dekurai\", \"discordian\", \"dracula-for-obsidian\", \"dracula-gemini\", \"dracula-lyt\", \"dracula-official\", \"dracula-plus\", \"dracula-slim\", \"dune\", \"dunite\", \"dynamic-color\"]" >> $GITHUB_OUTPUT
      - run: |
          echo "${{ steps.matrix.outputs.value }}"
  generate_preview:
    needs: [target_list]
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        value: ${{fromJSON(needs.target_list.outputs.matrix)}}
        color-scheme: [light, dark]
    steps:
      - name: Setup Directory
        run: mkdir runner_content
      - name: Clone Quartz Themes
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          path: runner_content/quartz-themes
      - name: Clone Quartz
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          repository: "jackyzha0/quartz"
          path: runner_content/quartz
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Setup Quartz Themes
        uses: nick-fields/retry@v3
        with:
          timeout_seconds: 15
          max_attempts: 3
          retry_on: error
          command: (./runner_content/quartz-themes ; npm install)
      - name: Set Theme
        working-directory: ./runner_content/quartz-themes
        run: npm run theme ${{ matrix.value }}
      - name: Setup Quartz
        working-directory: ./runner_content/quartz
        run: npm install
      - name: Setup Quartz Themes in Quartz
        working-directory: ./runner_content/quartz/quartz/styles
        run: sed -ir 's#@use "./base.scss";#@use "./base.scss";\n@use "./themes";#' custom.scss
      - name: Build Quartz
        working-directory: ./runner_content/quartz
        run: npx quartz build -d docs
      - name: Set light/dark mode
        working-directory: ./runner_content/quartz/public
        run: sed -ir 's/<html/<html saved-theme="${{matrix.color-scheme}}"/' index.html
      - name: Generate preview image
        uses: saberzero1/github-actions-screenshot@main
        with:
          url: "file://${{github.workspace}}/runner_content/quartz/public/index.html"
          output: "previews/${{matrix.value}}-${{matrix.color-scheme}}.png"
          viewportWidth: 1920
          viewportHeight: 1080
          waitForTimeout: 10000
          deviceScaleFactor: 1
          theme: "${{matrix.color-scheme}}"
      - name: Upload image
        uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.value}}-${{matrix.color-scheme}}
          path: "${{github.workspace}}/previews/*.png"
          overwrite: true
  combine_artifacts:
    runs-on: ubuntu-latest
    needs: generate_preview
    steps:
      - uses: actions/checkout@v4
      - name: Download previews' artifacts
        uses: actions/download-artifact@v4
        with:
          path: downloaded_artifacts
      - name: Unpack previews' artifacts
        working-directory: ${{github.workspace}}
        run: rsync -av ./downloaded_artifacts/*/* previews
      - name: Push preview images
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: previews/*.png
          skip_fetch: true
          skip_dirty_check: false
          commit_message: "[ci] previews: auto-updated"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
